name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REG_PASS: ${{ secrets.AZ_REGISTRY_PASSWORD }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build -t dockerimage .
        docker login -u ksarkar123987 -p ${{ env.REG_PASS }} ksarkar123987.azurecr.io
        docker tag dockerimage ksarkar123987.azurecr.io/test-repo:test-tag
        docker push ksarkar123987.azurecr.io/test-repo:test-tag
      
 
