name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t dockerimage .
  
  login:
   needs: build
   runs-on: ubuntu-latest
   steps:
   - uses: Azure/acr-build@v1
   - name: Docker Login
     run: |
      echo "test login"
      
 
