name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REG_PASS: ${{ secrets.AZ_REGISTRY_PASSWORD }}

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build the Docker image
      run: |
        docker build -t dockerimage .

    - name: Login to the registry
      run: |
        docker login -u ksarkar12398 -p ${{ env.REG_PASS }} ksarkar12398.azurecr.io

    - name: Push image to registry
      run: |
        docker tag dockerimage ksarkar12398.azurecr.io/test-repo:test-tag
        docker push ksarkar12398.azurecr.io/test-repo:test-tag


  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Azure login
      uses: Azure/login@v2.3.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Connect to AKS
      uses: Azure/cli@v2.1.0
      with:
        inlineScript: |
          az account set --subscription 719c1e53-b3fd-4af0-99f9-46469a324ca7
          az aks get-credentials --resource-group rg --name aks-cluster --overwrite-existing
      
 
