name: Docker Image CI

on:
  workflow_dispatch:

env:
  REG_PASS: ${{ secrets.AZ_REGISTRY_PASSWORD }}

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build the Docker image
      run: |
        docker build -t dockerimage .

    - name: Login to the registry
      run: |
        docker login -u ${{ vars.REGISTRY_NAME }} -p ${{ env.REG_PASS }} ${{ vars.REGISTRY_NAME }}.azurecr.io

    - name: Push image to registry
      run: |
        docker tag dockerimage ${{ vars.REGISTRY_NAME }}.azurecr.io/${{ vars.REPO_NAME }}:${{ vars.TAG_NAME }}
        docker push ${{ vars.REGISTRY_NAME }}.azurecr.io/${{ vars.REPO_NAME }}:${{ vars.TAG_NAME }}


  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Azure login
      uses: Azure/login@v2.3.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Connect AKS
      run: |
        az account set --subscription 719c1e53-b3fd-4af0-99f9-46469a324ca7
        az aks get-credentials --resource-group rg --name aks-cluster --overwrite-existing
    
    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/nginx.yml
        kubectl get pods

    - name: Describe the deployment
      run: |
        kubectl describe replicaset.apps/nginx-replicaset
      
 
