name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t dockerimage .
  
  login:
   needs: build
   runs-on: ubuntu-latest
   steps:
   - name: Docker Login
     run: |
      docker login -u ksarkar123987 -p HTw0ANOvotnoyZ6rKs5IDSbPsxLD9pE6p93+fVlmK++ACRCKglAV ksarkar123987.azurecr.io
      
 
